### ISSUE TITLE
why does this library exist?

### ISSUE THREAD

**Issue by Pyrolistical** [myndzi/supertest-promised#1]
https://github.com/WhoopInc/supertest-as-promised does the same thing and is more popular

**Comment by myndzi** [comment]
Because, at the time that I wrote this, I had some problem or other with `supertest-as-promised`. Maybe out of date Bluebird? I was going to submit a PR, but wound up almost rewriting it, so I just published the result. You're quite welcome to use that library if you prefer. Note that should.js has promise support built in these days so they're both obsolete.
